### PR TITLE
Correct errors

### PR DESCRIPTION
**Pull request by pavshuk**
I create a model with relations 'childObjects' MANY_MANY .
To edit this model i add field 'childObjectsIds' and in action 'beforeSave' i modify 'childObjects'.

With standart forms it`s work, but now i get error:

if($fields===array())
throw new CDbException(Yii::t('yii','No columns are being updated for table "{table}".',

in CDbCommandBuilder on 290 line.

### CODE REVIEW

**Comment by pavshuk** [comment]
So sorry, I was wrong, it must be deleted

**Comment by vitalets** [comment]
so, have you got it working with MANY-MANY relation?

**Comment by pavshuk** [comment]
Today I will make all code and post it.
07.06.2013 12:28 ÐÏÌØÚÏ×ÁÔÅÌØ "Vitaliy Potapov" notifications@github.com
ÎÁÐÉÓÁÌ:

**Comment by pavshuk** [comment]
Model :

```
class Client extends CActiveRecord
{
public function behaviors(){
    return 
    array_merge(parent::behaviors(),
    array(
        'DMultiplyListBehavior'=>array(
            'class'=>'DMultiplyListBehavior',
            'attribute'=>'rentVariantTypeIds', //variable which I declare in behavior
            'relation'=>'rel_rent_variant_type',
            'relationPk'=>'rvtid',
            'RelationClass' => 'RentVariantType'
        ),  
    ));
}
}



'type' => 'text',
'model' => $this,
'mode' => 'inline',
'attribute' => 'rentVariantTypeIds',
'emptytext' => $this->getLabel($name),
'url' => Yii::app()->createUrl('/'.$this->getClassId().'/updateEditable'),
'showbuttons' => false,
'options' => array(
    'onblur' => 'submit',
),
'type'  => 'checklist',
'source' => RentVariantType::getRentVariantTypeAllValue(),
```

There I fount two problems:

Here I found 2 problems.

EditableSaver
in function Update() I make next changes.

https://github.com/pavshuk/x-editable-yii/commit/64fa06f93fdaa3d36ee49dfea055017174a4a061#diff-0

Another way sqlbuilder says that no field`s to saving.

And other problem to show defaults values
In EditableField init() function

https://github.com/pavshuk/x-editable-yii/commit/d688ee5b2b0b5f699436188e53420af3f5502d1b

there $this->model->getAttribute($this->attribute) don't get behavior variables. Have I made right decision?  Or it`s must be another way?

All this changes in repository. If it all right a will made pull request.

Sorry for my English.

**Comment by vitalets** [comment]
@pavshuk  thanks for that pr!
could you check with new 1.3 version?

**Comment by pavshuk** [comment]
works correct.

**Pull request merged**
