### PR TITLE
Update x-editable lib

### PR DESCRIPTION
**Pull request by magefad**

### CODE REVIEW

**Comment by vitalets** [comment]
hi, thanks for PR! 
I plan to make big update of this lib with release of x-editable 1.4.4. 
There are also changes on php part, so it's not enough to update x-editable js.
Hope to finish it on this week.

**Comment by magefad** [comment]
wheeeeen

**Comment by vitalets** [comment]
hi, @magefad !
I'm trying to do my best.. X-editable 1.4.5 is ready in `dev` branch. I need to check new features with yii version and then release both libs. 
This or next week.. I hope.

**Comment by magefad** [comment]
1.4.5?
1.4.4 x-editable released, cool
But when x-editable-yii now? :(

**Comment by vitalets** [comment]
oops, 1.4.4 of course )
Yii version is going on, the only remaining issue - https://github.com/vitalets/x-editable-yii/pull/23.
I really hope to release on 9 may holidays.

**Comment by magefad** [comment]
Waiting for the past month

**Comment by magefad** [comment]
:(

**Comment by vitalets** [comment]
done :)

**Pull request closed without merging**
