### PR TITLE
evaluate column value before testing it's length

### PR DESCRIPTION
**Pull request by gregmolnar**
fix for #55

### CODE REVIEW

**Comment by vitalets** [comment]
hi @gregmolnar, 
could you give a bit more description why we should evaluate `value`?
For me it seems that `renderDataCellContent` will do it automatically, and we just check if `value` provided or not in column config..

**Comment by gregmolnar** [comment]
Hi 
The issue is when you do strlen on the value here: https://github.com/vitalets/x-editable-yii/blob/master/EditableColumn.php#L52 if the value is a callback function than strlen will throw an error. 
Maybe we could change strlen() to empty() as that won't throw an error in case of a function.

**Comment by vitalets** [comment]
I get it, thanks.You are setting `'value': function() { ... }`.
yes, we can use empty() for sure.

**Comment by gregmolnar** [comment]
I will a new PR with empty() in a bit. Closing this.

**Comment by gregmolnar** [comment]
I see you just fixed it. Thanks.

**Comment by vitalets** [comment]
Sorry, didn't see you comment =)
anyway thanks!

**Pull request closed without merging**
